services:
  - type: web
    name: thesacreddrop-leaderboard
    env: node
    buildCommand: |
      cd backend && npm install
      cd ../frontend && npm install && npm run build
    startCommand: cd backend && NODE_ENV=production node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /api/test 